// Generated by CoffeeScript 1.7.1
(function() {
  describe('GoogleMaps', function() {
    return describe('#load()', function() {
      it.skip('should throw an error if promise style is used', function() {
        return expect(function() {
          return GoogleMapsLoader.load().then();
        }).to["throw"](Error, 'Using promises is not supported anymore. Please take a look in new documentation and use callback instead.');
      });
      return it('should load google api object', function(done) {
        return GoogleMapsLoader.load(function(google) {
          expect(google).to.be.a('object');
          expect(google).to.have.keys(['maps']);
          return done();
        });
      });
    });
  });

}).call(this);
